use new_hr_db;

DELIMITER $$

CREATE FUNCTION getFullName(firstname VARCHAR(50), lastname VARCHAR(50))
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
	DECLARE FULL_NAME VARCHAR(50);
	SET FULL_NAME = concat(firstname, " ", lastname);
    
    RETURN FULL_NAME;
END $$

DELIMITER ;

select * from tbl_employees;
-- query 1
SELECT concat(FIRST_NAME, " ", LAST_NAME) AS FULL_NAME, SALARY FROM Tbl_Employees WHERE SALARY < 6000;

-- QUERY 2
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY FROM Tbl_Employees WHERE SALARY > 8000;

-- QUERY 3
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM Tbl_Employees WHERE LAST_NAME = "McEwen";

-- QUERY 4
SELECT * FROM Tbl_Employees WHERE DEPARTMENT_ID IS NULL;

-- QUERY 5
SELECT * FROM Tbl_Departments where DEPARTMENT_NAME = "Marketing";

-- QUERY 6
SELECT concat(FIRST_NAME, " ", LAST_NAME) AS FULL_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE 'M%' ORDER BY DEPARTMENT_ID ASC;

-- QUERY 7
SELECT * FROM TBL_EMPLOYEES WHERE (SALARY BETWEEN 8000 AND 12000 AND COMMISSION_PCT > 0.00) OR (HIRE_DATE < '2003-06-05' AND DEPARTMENT_ID NOT IN (40, 120, 70));

-- QUERY 8
SELECT concat(FIRST_NAME, " ", LAST_NAME) AS FULL_NAME, SALARY, COMMISSION_PCT FROM TBL_EMPLOYEES WHERE COMMISSION_PCT <= 0.00;

-- QUERY 9
SELECT getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, EMAIL, PHONE_NUMBER, SALARY FROM TBL_EMPLOYEES WHERE SALARY BETWEEN 9000 AND 17000;

-- QUERY 10
SELECT FIRST_NAME, LAST_NAME, SALARY FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE '%M';

-- QUERY 11
SELECT getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, SALARY FROM TBL_EMPLOYEES WHERE SALARY NOT BETWEEN 7000 AND 15000 ORDER BY FULL_NAME;

-- QUERY 12
SELECT getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, JOB_ID, HIRE_DATE FROM TBL_EMPLOYEES WHERE HIRE_DATE BETWEEN '2007-11-05' AND '2009-07-05' ORDER BY HIRE_DATE ASC;

-- QUERY 13
SELECT getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID IN (70, 90);

-- QUERY 14
SELECT getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, SALARY, MANAGER_ID FROM TBL_EMPLOYEES WHERE MANAGER_ID != 0 OR MANAGER_ID = EMPLOYEE_ID;

-- QUERY 15
SELECT * FROM TBL_EMPLOYEES WHERE HIRE_DATE < '2002-06-21';

-- QUERY 16
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY, MANAGER_ID FROM TBL_EMPLOYEES WHERE MANAGER_ID IN (120, 103, 145);

-- QUERY 17
SELECT * FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE "%D%" OR FIRST_NAME LIKE "%S%" OR FIRST_NAME LIKE "%N%";

-- QUERY 18
SELECT 
getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, 
HIRE_DATE, COMMISSION_PCT, EMAIL, 
REPLACE(PHONE_NUMBER, "-", "") AS PHONE, SALARY 
FROM TBL_EMPLOYEES WHERE SALARY > 11000 OR SUBSTRING(PHONE_NUMBER, 7, 1) = '3';

-- QUERY 19
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM TBL_EMPLOYEES where SUBSTRING(FIRST_NAME, 3, 1) = "s";

-- QUERY 20
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID NOT IN (50,30,80);

-- QUERY 21
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID IN (30,40,90);

-- QUERY 22
SELECT EMPLOYEE_ID FROM TBL_JOBHISTORY GROUP BY EMPLOYEE_ID HAVING COUNT(EMPLOYEE_ID) >= 2; 

-- QUERY 23
-- SELECT JOB_ID, count(EMPLOYEE_ID) AS EMPLOYEE_COUNT, sum(SALARY) AS TOTAL_SALARY, 
-- MAX(SALARY) - MIN(SALARY) AS SALARY_DIFFERENCE FROM TBL_EMPLOYEES GROUP BY JOB_ID; 
SELECT 
    e.JOB_ID, 
    j.JOB_TITLE,
    COUNT(e.EMPLOYEE_ID) AS employee_count, 
    SUM(e.SALARY) AS total_salary, 
    j.max_salary - j.min_salary AS salary_difference
FROM Tbl_Employees e
JOIN Tbl_Jobs j ON e.JOB_ID = j.JOB_ID
GROUP BY e.JOB_ID, j.JOB_TITLE;

-- QUERY 24
SELECT JOB_ID FROM TBL_JOBHISTORY WHERE datediff(END_DATE, START_DATE) > 300 GROUP BY JOB_ID HAVING COUNT(EMPLOYEE_ID) >= 2;

-- QUERY 25
SELECT COUNTRY_ID, COUNT(CITY) FROM TBL_LOCATIONS GROUP BY COUNTRY_ID;

-- QUERY 26
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) FROM TBL_EMPLOYEES WHERE MANAGER_ID != 0 AND EMPLOYEE_ID != MANAGER_ID group by MANAGER_ID;

-- 27
SELECT * FROM TBL_JOBS ORDER BY JOB_TITLE DESC;

-- 28
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM TBL_EMPLOYEES WHERE JOB_ID IN ('SA_MAN', 'SA_REP');

-- 29
SELECT DEPARTMENT_ID, AVG(SALARY) FROM TBL_EMPLOYEES WHERE COMMISSION_PCT > 0.00 GROUP BY DEPARTMENT_ID;

-- 30
SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID) >= 4;

-- 31
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) FROM TBL_EMPLOYEES WHERE COMMISSION_PCT > 0.00 GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID) >= 10; 

-- 32
SELECT EMPLOYEE_ID, END_DATE FROM TBL_JOBHISTORY WHERE END_DATE IS NOT NULL;

-- 33
SELECT * FROM TBL_EMPLOYEES WHERE COMMISSION_PCT = 0.00 AND SALARY BETWEEN 7000 AND 12000 AND DEPARTMENT_ID = 50;

-- 34
SELECT JOB_ID, AVG(SALARY) FROM TBL_EMPLOYEES GROUP BY JOB_ID HAVING AVG(SALARY) <= 8000;

-- 35
SELECT JOB_TITLE, MAX_SALARY - MIN_SALARY AS DIFFERENCE FROM TBL_JOBS WHERE MAX_SALARY - MIN_SALARY BETWEEN 12000 AND 18000;

-- 36
SELECT FIRST_NAME, LAST_NAME FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE "d%" OR LAST_NAME LIKE "d%";

-- 37
SELECT * FROM TBL_JOBS WHERE MIN_SALARY > 9000;

-- 38
SELECT * FROM TBL_EMPLOYEES WHERE HIRE_DATE > "1987-09-07";

-- 39
SELECT FIRST_NAME, LAST_NAME, SALARY FROM TBL_EMPLOYEES 
WHERE SALARY > (SELECT SALARY FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID = "163");

-- 40
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOB_ID FROM TBL_EMPLOYEES 
WHERE JOB_ID = (SELECT JOB_ID FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID = "169");

-- 41
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY = (SELECT MIN(SALARY) FROM TBL_EMPLOYEES);

-- 42
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM TBL_EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES);

-- 43
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, manager_id FROM TBL_EMPLOYEES WHERE MANAGER_ID = (SELECT employee_id FROM TBL_EMPLOYEES WHERE FIRST_NAME = "Payam");

-- 44
SELECT E.FIRST_NAME, E.DEPARTMENT_ID, E.JOB_ID, D.DEPARTMENT_NAME FROM TBL_EMPLOYEES E 
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE D.DEPARTMENT_NAME = "FINANCE";

-- 45
SELECT * FROM TBL_EMPLOYEES WHERE SALARY = 3000 AND MANAGER_ID = 121;

-- 46
SELECT * FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID IN ('134', '159', '183');

-- 47
SELECT * FROM TBL_EMPLOYEES WHERE SALARY BETWEEN 1000 AND 3000;

-- 48
SELECT * FROM TBL_EMPLOYEES WHERE SALARY IN ((SELECT MIN(SALARY) FROM TBL_EMPLOYEES), '2500');

-- 49
SELECT * FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID 
NOT IN (SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS 
WHERE MANAGER_ID BETWEEN 100 AND 200);

-- 50
SELECT * FROM TBL_EMPLOYEES WHERE SALARY < 
(SELECT MAX(SALARY) FROM TBL_EMPLOYEES) ORDER BY SALARY DESC LIMIT 1;

-- 51
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE FIRST_NAME = "Clara") 
AND FIRST_NAME != 'Clara';

-- 52
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE "%T%";

-- 53
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM TBL_EMPLOYEES WHERE FIRST_NAME LIKE "%J%" AND SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES);

-- 54
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS WHERE LOCATION_ID = '1800');

-- 55
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM TBL_EMPLOYEES WHERE SALARY < (SELECT SALARY FROM TBL_EMPLOYEES WHERE JOB_ID = "MK_MAN");

-- 56
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM TBL_EMPLOYEES WHERE SALARY < (SELECT SALARY FROM TBL_EMPLOYEES WHERE JOB_ID = "MK_MAN") AND JOB_ID != "MK_MAN";

-- 57
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM TBL_EMPLOYEES WHERE SALARY > (SELECT SALARY FROM TBL_EMPLOYEES WHERE JOB_ID = "PU_MAN") AND JOB_ID != "MK_MAN";

-- 58
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID 
FROM TBL_EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES GROUP BY DEPARTMENT_ID LIMIT 1);

-- 59
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID 
FROM TBL_EMPLOYEES WHERE SALARY > 3700;

-- 60
SELECT DEPARTMENT_ID, SUM(SALARY) AS TOTAL_SALARY
FROM TBL_EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID) > 1;

-- 61
SELECT EMPLOYEE_ID, getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, 
CASE 
WHEN JOB_ID = "ST_MAN" THEN 'SALESMAN'
WHEN JOB_ID = "IT_PROG" THEN 'DEVELOPER'
ELSE JOB_ID
END AS MODIFIED_JOB_TITLE
FROM TBL_EMPLOYEES;

-- 62
SELECT EMPLOYEE_ID, getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, 
CASE 
WHEN SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) THEN 'HIGH'
WHEN SALARY < (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) THEN 'LOW'
END AS SALARYSTATUS
FROM TBL_EMPLOYEES;

-- 63
SELECT EMPLOYEE_ID, getFullName(FIRST_NAME, LAST_NAME) AS FULL_NAME, 
SALARY, SALARY - (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) AS AVGCOMPARE,
CASE
WHEN SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) THEN 'HIGH'
WHEN SALARY < (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) THEN 'LOW'
END AS SALARYSTATUS
FROM TBL_EMPLOYEES;

-- 64
SELECT DEPARTMENT_NAME FROM TBL_DEPARTMENTS WHERE 
DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES 
GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID) >= 1);

-- 65
SELECT FIRST_NAME, DEPARTMENT_ID
FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID in 
(SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS WHERE LOCATION_ID 
IN (SELECT LOCATION_ID FROM TBL_LOCATIONS WHERE COUNTRY_ID LIKE "%UK%"));

-- 66
SELECT LAST_NAME, DEPARTMENT_ID
FROM TBL_EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES)
AND DEPARTMENT_ID in 
(SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS WHERE DEPARTMENT_NAME LIKE "%IT%");

-- 67
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM TBL_EMPLOYEES WHERE SALARY > 
(SELECT SALARY FROM TBL_EMPLOYEES WHERE LAST_NAME = "Ozer") 
ORDER BY LAST_NAME ASC;

-- 68
SELECT FIRST_NAME, LAST_NAME, MANAGER_ID, DEPARTMENT_ID
FROM TBL_EMPLOYEES WHERE MANAGER_ID in 
(SELECT MANAGER_ID FROM TBL_DEPARTMENTS WHERE LOCATION_ID 
IN (SELECT LOCATION_ID FROM TBL_LOCATIONS WHERE COUNTRY_ID LIKE "%US%"));

-- 69
SELECT FIRST_NAME, LAST_NAME
FROM TBL_EMPLOYEES E WHERE SALARY > 
(SELECT 0.5 * SUM(SALARY) FROM TBL_EMPLOYEES 
WHERE DEPARTMENT_ID = E.DEPARTMENT_ID GROUP BY DEPARTMENT_ID);

-- 70
SELECT * FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM TBL_EMPLOYEES);

-- 71
SELECT * FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID IN (SELECT MANAGER_ID FROM TBL_DEPARTMENTS);

-- 72
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY, D.DEPARTMENT_NAME, L.CITY
FROM TBL_EMPLOYEES E 
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.HIRE_DATE BETWEEN '2002-01-01' AND '2003-12-31' 
AND E.SALARY = (SELECT MAX(SALARY) FROM TBL_EMPLOYEES);

-- 73
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM TBL_DEPARTMENTS WHERE LOCATION_ID 
= (SELECT LOCATION_ID FROM TBL_LOCATIONS WHERE CITY = "LONDON");

-- 74
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) ORDER BY SALARY DESC;

-- 75
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY > (SELECT MAX(SALARY) FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = "40");

-- 76
SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM TBL_DEPARTMENTS WHERE LOCATION_ID 
= (SELECT LOCATION_ID FROM TBL_DEPARTMENTS WHERE DEPARTMENT_ID = '30');

-- 77
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE MANAGER_ID = "201");

-- 78
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY = (SELECT SALARY FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = "40");

-- 79
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM TBL_EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS WHERE DEPARTMENT_NAME = 'Marketing');

-- 80
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY > (SELECT MIN(SALARY) FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = "40");

-- 81
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM TBL_EMPLOYEES
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID = '165');

-- 82
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY < (SELECT MIN(SALARY) FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = "70");

-- 83
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES 
WHERE SALARY < (SELECT AVG(SALARY) FROM TBL_EMPLOYEES) AND 
DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE FIRST_NAME = "Clara");

-- 84
SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS WHERE LOCATION_ID 
= (SELECT LOCATION_ID FROM TBL_LOCATIONS WHERE CITY = "LONDON"));

-- 85
SELECT CITY FROM TBL_LOCATIONS WHERE LOCATION_ID = 
(SELECT LOCATION_ID FROM TBL_DEPARTMENTS WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID = '134'));

-- 86
SELECT * FROM TBL_DEPARTMENTS WHERE DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES WHERE (SELECT MAX(SALARY) FROM TBL_EMPLOYEES) >= 7000
 AND EMPLOYEE_ID IN 
(SELECT EMPLOYEE_ID FROM TBL_JOBHISTORY 
GROUP BY EMPLOYEE_ID HAVING COUNT(EMPLOYEE_ID) >= 1));

-- 87
SELECT * FROM TBL_DEPARTMENTS WHERE DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID FROM TBL_EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MIN(SALARY) >= 8000);

-- 88
SELECT getFullName(FIRST_NAME, LAST_NAME) AS MANAGER_NAME, DEPARTMENT_ID FROM TBL_EMPLOYEES E
WHERE MANAGER_ID IN (SELECT MANAGER_ID FROM TBL_EMPLOYEES 
GROUP BY MANAGER_ID HAVING COUNT(EMPLOYEE_ID) >= 4);

-- 89
SELECT * FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID = 
(SELECT EMPLOYEE_ID FROM TBL_JOBHISTORY WHERE JOB_ID = "SA_REP");

-- 90
SELECT * FROM TBL_EMPLOYEES
WHERE SALARY = (SELECT SALARY FROM TBL_EMPLOYEES ORDER BY SALARY ASC LIMIT 1 OFFSET 1);

SELECT SALARY FROM TBL_EMPLOYEES ORDER BY SALARY ASC LIMIT 1 OFFSET 1;

-- 91
SELECT * FROM TBL_DEPARTMENTS WHERE MANAGER_ID = 
(SELECT EMPLOYEE_ID FROM TBL_EMPLOYEES WHERE FIRST_NAME = "SUSAN");

-- 92
SELECT DEPARTMENT_ID, getFullName(FIRST_NAME, LAST_NAME) AS EMPLOYEE_NAME, SALARY 
FROM TBL_EMPLOYEES E WHERE SALARY IN (SELECT MAX(SALARY) FROM TBL_EMPLOYEES 
WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) ORDER BY DEPARTMENT_ID;

SELECT MAX(SALARY), DEPARTMENT_ID FROM TBL_EMPLOYEES GROUP BY DEPARTMENT_ID;

-- 93
SELECT * FROM TBL_EMPLOYEES WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM TBL_JOBHISTORY);

-- 94
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM TBL_EMPLOYEES E JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM TBL_EMPLOYEES WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM TBL_DEPARTMENTS);

-- 95
SELECT E.FIRST_NAME, E.LAST_NAME, D.*, L.CITY, L.STATE_PROVINCE
FROM TBL_EMPLOYEES E JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

-- 96
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.*
FROM TBL_EMPLOYEES E JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID;

-- 97
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM TBL_EMPLOYEES E JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE E.DEPARTMENT_ID IN ('80', '40');

-- 98
SELECT E.FIRST_NAME, E.LAST_NAME, D.*, L.CITY, L.STATE_PROVINCE
FROM TBL_EMPLOYEES E JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID WHERE E.FIRST_NAME LIKE "%Z%";

-- 99
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM TBL_EMPLOYEES E RIGHT JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 100
SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.SALARY
FROM TBL_EMPLOYEES E1 JOIN TBL_EMPLOYEES E2 ON E2.EMPLOYEE_ID = 182
WHERE E1.SALARY < E2.SALARY;

-- 101
SELECT E1.*, E2.FIRST_NAME AS MANAGER_NAME
FROM TBL_EMPLOYEES E1 JOIN TBL_EMPLOYEES E2 
ON E2.EMPLOYEE_ID = E1.MANAGER_ID WHERE E1.MANAGER_ID != 0;

-- 102
SELECT D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM TBL_DEPARTMENTS D JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

-- 103
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM TBL_EMPLOYEES E LEFT JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 104
SELECT E1.*, E2.FIRST_NAME AS MANAGER_NAME
FROM TBL_EMPLOYEES E1 JOIN TBL_EMPLOYEES E2 
ON E2.MANAGER_ID = E1.MANAGER_ID WHERE E1.MANAGER_ID = 0;

-- 105
SELECT E1.FIRST_NAME, E1.LAST_NAME, E1.DEPARTMENT_ID
FROM TBL_EMPLOYEES E1 JOIN TBL_EMPLOYEES E2 
ON E2.DEPARTMENT_ID = E1.DEPARTMENT_ID WHERE E2.LAST_NAME = "TAYLOR";

-- 106
SELECT 
J.JOB_TITLE, D.DEPARTMENT_NAME, 
JH.START_DATE AS JOINING_DATE, 
getFullName(E.FIRST_NAME, E.LAST_NAME) AS EMPLOYEE_NAME
FROM TBL_EMPLOYEES E 
JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID 
JOIN TBL_JOBHISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE JH.START_DATE BETWEEN '1993-01-01' AND '1997-12-31';

-- 107
SELECT
J.JOB_TITLE, 
getFullName(E.FIRST_NAME, E.LAST_NAME) AS EMPLOYEE_NAME,
J.MAX_SALARY - E.SALARY AS SALARY_DIFFERENCE
FROM TBL_EMPLOYEES E 
JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID;

-- 108
SELECT AVG(E.SALARY) AS AVERAGE_SALARY, COUNT(E.EMPLOYEE_ID), D.DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM TBL_EMPLOYEES E 
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.COMMISSION_PCT > 0.00 GROUP BY E.DEPARTMENT_ID;

-- 109
SELECT
J.JOB_TITLE, 
getFullName(E.FIRST_NAME, E.LAST_NAME) AS EMPLOYEE_NAME,
J.MAX_SALARY - E.SALARY AS SALARY_DIFFERENCE
FROM TBL_EMPLOYEES E 
JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID WHERE E.DEPARTMENT_ID = 80;

-- 110
SELECT
D.DEPARTMENT_NAME,
L.CITY,
C.COUNTRY_NAME
FROM TBL_COUNTRIES C
JOIN TBL_LOCATIONS L ON L.COUNTRY_ID = C.COUNTRY_ID
JOIN TBL_DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID;

-- 111
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME 
FROM TBL_EMPLOYEES E JOIN TBL_DEPARTMENTS D ON E.EMPLOYEE_ID = D.MANAGER_ID;

-- 112
SELECT AVG(E.SALARY), J.JOB_TITLE 
FROM TBL_EMPLOYEES E JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID GROUP BY E.JOB_ID;

-- 113
SELECT 
E.EMPLOYEE_ID,
J.JOB_ID, D.DEPARTMENT_ID, 
JH.START_DATE, JH.END_DATE
FROM TBL_EMPLOYEES E 
JOIN TBL_JOBS J ON E.JOB_ID = J.JOB_ID 
JOIN TBL_JOBHISTORY JH ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY >= 12000;

-- 114
SELECT 
C.COUNTRY_NAME, L.CITY, COUNT(D.DEPARTMENT_ID) AS DEPARTMENTS_COUNT
FROM
TBL_COUNTRIES C
JOIN TBL_LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN TBL_DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID 
JOIN TBL_EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY C.COUNTRY_NAME, L.CITY HAVING COUNT(EMPLOYEE_ID) >= 2;

-- 115
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM TBL_EMPLOYEES E 
JOIN TBL_DEPARTMENTS D ON E.EMPLOYEE_ID = D.MANAGER_ID
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

-- 116
SELECT 
    E.EMPLOYEE_ID,
    J.JOB_TITLE,
    DATEDIFF(JH.END_DATE, JH.START_DATE) AS NUMBER_OF_DAYS_WORKED
FROM 
    TBL_EMPLOYEES E
JOIN 
    Tbl_JobHistory jh ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID
JOIN 
    Tbl_Jobs j ON jh.JOB_ID = j.JOB_ID
WHERE 
    e.DEPARTMENT_ID = 80;

-- 117
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM TBL_EMPLOYEES E 
JOIN TBL_DEPARTMENTS D ON E.EMPLOYEE_ID = D.MANAGER_ID
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID WHERE L.CITY = "LONDON";

-- 118
SELECT 
    E.EMPLOYEE_ID,
    J.JOB_TITLE,
    JH.START_DATE, JH.END_DATE
FROM 
    TBL_EMPLOYEES E
JOIN 
    Tbl_JobHistory jh ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID
JOIN 
    Tbl_Jobs j ON jh.JOB_ID = j.JOB_ID
WHERE 
    e.COMMISSION_PCT = 0.00;
    
-- 119
SELECT
D.DEPARTMENT_NAME, D.DEPARTMENT_ID,
COUNT(E.EMPLOYEE_ID) AS NUMBER_OF_EMPS
FROM TBL_EMPLOYEES E
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY E.DEPARTMENT_ID;

-- 120
SELECT 
E.FIRST_NAME, E.LAST_NAME, E.EMPLOYEE_ID, C.COUNTRY_NAME
FROM
TBL_EMPLOYEES E
JOIN TBL_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN TBL_LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID 
JOIN TBL_COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID;

